---
name: Formalización y Abordajes
locale: es
type: learning
beta: false
teacher_info: ''
language: text
id_format: "%05d"
order:
- 2
- 3
- 4
- 5
- 6
- 21
- 8
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 22
- 17
- 23
- 20
- 19
