---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: El ajedrez, carrera de mente, clue y juego de la oca requieren más tiempo
    para su finalización
  checked: false
- value: Las personas en edad adulta prefieren el ajedrez, el clue y el carrera de
    mente
  checked: true
- value: L@s adolescentes prefieren el clue y el 4 en linea
  checked: true
- value: L@s pequeñ@s en edad primaria prefieren el operation, el clue y el juego
    de la oca
  checked: true
- value: L@s pequeñ@s en edad inicial prefieren el rompecabezas y bingo
  checked: true
- value: El 4 en línea y ajedrez están pensados para 2 jugadores, el resto a partir
    de 2
  checked: true
- value: El juego de la oca, el bingo y el carrera de mente manejan el azar como componente
  checked: false
- value: El juego de ajedrez y el 4 en línea son juegos de lógica
  checked: true
name: Buscando patrones
