---
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
manual_evaluation: false
choices:
- value: Necesidad de crear un sistema de diagn칩stico de l@s estudiantes
  checked: true
- value: Evaluar los mecanismos de acompa침amiento institucional
  checked: true
- value: Optimizar el almacenamiento de informaci칩n para que sea funcional
  checked: true
- value: Evaluar y desarrollar espacios de di치logo con el estudiantado
  checked: true
name: Partiendo el problema en subproblemas
